[project]
name = "Mahjongg-Core"
requires-python = ">= 3.13"

authors = [{ name = "John Orchard", email = "jtorchard@protonmail.com" }]

description = "Core implementation of Mahjong"

readme = "README.md"

license = {file = "LICENSE"}

[tool.ruff.lint]
extend-select = ["I"]
