[project]
requires-python = ">= 3.11"

authors = [
  {name = "John Orchard", email = "jtorchard@protonmail.com"},
]

description = "Core implementation of Mahjong"

readme = "README.md"

license = {text = "MIT License"}

[project.optional-dependencies]
typing = ["mypy>=1.13.0"]

[tool.ruff.lint]
extend-select = ["I"]
